package com.mibo.modules.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDeviceLaying<M extends BaseDeviceLaying<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDeviceId(java.lang.Integer deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}
	
	public java.lang.Integer getDeviceId() {
		return getInt("device_id");
	}

	public M setStaTime(java.lang.String staTime) {
		set("sta_time", staTime);
		return (M)this;
	}
	
	public java.lang.String getStaTime() {
		return getStr("sta_time");
	}

	public M setEndTime(java.lang.String endTime) {
		set("end_time", endTime);
		return (M)this;
	}
	
	public java.lang.String getEndTime() {
		return getStr("end_time");
	}

	public M setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
		return (M)this;
	}
	
	public java.util.Date getAddTime() {
		return get("add_time");
	}

}
