package com.mibo.modules.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserScene<M extends BaseUserScene<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGatewayId(java.lang.Integer gatewayId) {
		set("gateway_id", gatewayId);
		return (M)this;
	}
	
	public java.lang.Integer getGatewayId() {
		return getInt("gateway_id");
	}

	public M setSceneType(java.lang.Integer sceneType) {
		set("scene_type", sceneType);
		return (M)this;
	}
	
	public java.lang.Integer getSceneType() {
		return getInt("scene_type");
	}

	public M setSceneName(java.lang.String sceneName) {
		set("scene_name", sceneName);
		return (M)this;
	}
	
	public java.lang.String getSceneName() {
		return getStr("scene_name");
	}

	public M setSceneData(java.lang.String sceneData) {
		set("scene_data", sceneData);
		return (M)this;
	}
	
	public java.lang.String getSceneData() {
		return getStr("scene_data");
	}

	public M setSceneImg(java.lang.String sceneImg) {
		set("scene_img", sceneImg);
		return (M)this;
	}
	
	public java.lang.String getSceneImg() {
		return getStr("scene_img");
	}

	public M setIsHome(java.lang.Boolean isHome) {
		set("is_home", isHome);
		return (M)this;
	}
	
	public java.lang.Boolean getIsHome() {
		return get("is_home");
	}

	public M setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
		return (M)this;
	}
	
	public java.util.Date getAddTime() {
		return get("add_time");
	}

}
