package com.mibo.modules.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserGateway<M extends BaseUserGateway<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setGatewayId(java.lang.Integer gatewayId) {
		set("gateway_id", gatewayId);
		return (M)this;
	}
	
	public java.lang.Integer getGatewayId() {
		return getInt("gateway_id");
	}

	public M setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
		return (M)this;
	}
	
	public java.util.Date getAddTime() {
		return get("add_time");
	}

}
