package com.mibo.modules.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDeviceMsg<M extends BaseDeviceMsg<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDeviceId(java.lang.Integer deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}
	
	public java.lang.Integer getDeviceId() {
		return getInt("device_id");
	}

	public M setPayload(java.lang.String payload) {
		set("payload", payload);
		return (M)this;
	}
	
	public java.lang.String getPayload() {
		return getStr("payload");
	}

	public M setMessageType(java.lang.String messageType) {
		set("message_type", messageType);
		return (M)this;
	}
	
	public java.lang.String getMessageType() {
		return getStr("message_type");
	}

	public M setTopic(java.lang.String topic) {
		set("topic", topic);
		return (M)this;
	}
	
	public java.lang.String getTopic() {
		return getStr("topic");
	}

	public M setMsgTime(java.util.Date msgTime) {
		set("msg_time", msgTime);
		return (M)this;
	}
	
	public java.util.Date getMsgTime() {
		return get("msg_time");
	}

}
