package com.mibo.modules.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDeviceSwitch<M extends BaseDeviceSwitch<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDeviceId(java.lang.Integer deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}
	
	public java.lang.Integer getDeviceId() {
		return getInt("device_id");
	}

	public M setPlaceNo(java.lang.Integer placeNo) {
		set("place_no", placeNo);
		return (M)this;
	}
	
	public java.lang.Integer getPlaceNo() {
		return getInt("place_no");
	}

	public M setSwitchState(java.lang.Boolean switchState) {
		set("switch_state", switchState);
		return (M)this;
	}
	
	public java.lang.Boolean getSwitchState() {
		return get("switch_state");
	}

}
